### ISSUE TITLE
Base branch for PR should handle any value

### ISSUE THREAD

**Issue by PDoakORNL** [biddisco/pycicle#27]
This will include refactoring master => base MASTER => BASE where appropriate to avoid confusion.  It should not break hpx.

**Comment by PDoakORNL** [comment]
It's worth thinking about whether we want to build all PR's regardless of base of how we might want to handle that.  Right now you need one instance and one config directory per base branch.  This has the advantage of being relatively simple and supporting branches with different build requirements.

**Comment by biddisco** [comment]
Also. Currently, we only test PRs that are marked as 'mergeable' on github. It assumes that master is the reference branch, so when testing PRs against another branch, we probably need to add an extra check to see if `PR+branch != conflcts` and then only test if that holds.

I didn't quite understand what you meant in your first comment 
> master => base MASTER => BASE
Could you please elucidate?

**Comment by PDoakORNL** [comment]
I meant all python variables became base variables, all config variables with MASTER became BASE variables but "master" literal defaults for those variables did not.

**Comment by PDoakORNL** [comment]
I have a PR based on rational_config_handling that fixes this mergable issue.  I've verified its checking the base branch and not the master for mergeable.
